export const customerDataList = [
  {
    Id: "1",
    image: "https://docs.material-tailwind.com/img/team-3.jpg",
    name: "Amir Kingstone",
    email: "amir@gmail.com",
    phone: "+255 675 342 345",
    address: "Tanzania, Dar es Salaam, Makumbusho",
  },
  {
    Id: "2",
    image: "/assets/deki.png",
    name: "Milo Jack",
    email: "jibumwakilembe@gmail.com",
    phone: "+255 675 342 345",
    address: "Tanzania, Dar es Salaam, Makumbusho",
  },
  {
    Id: "3",
    image: "/assets/mtu3.png",
    name: "Sam Patrick",
    email: "amir@gmail.com",
    phone: "+255 675 342 345",
    address: "Tanzania, Dar es Salaam, Makumbusho",
  },
  {
    Id: "4",
    image: "https://docs.material-tailwind.com/img/team-3.jpg",
    name: "Amir Kingstone",
    email: "answerjibu@gmail.com",
    phone: "+255 675 342 345",
    address: "Tanzania, Dar es Salaam, Makumbusho",
  },
  {
    Id: "5",
    image: "/assets/mtu5.png",
    name: "Amir Kingstone",
    email: "amirKingstons@gmail.com",
    phone: "+255 675 342 345",
    address: "Tanzania, Dar es Salaam, Makumbusho",
  },
  {
    Id: "6",
    image: "/assets/mtu6.png",
    name: "Jane Kitunge",
    email: "amir@gmail.com",
    phone: "+255 675 342 345",
    address: "Tanzania, Dar es Salaam, Makumbusho",
  },
  {
    Id: "7",
    image: "/assets/mtu1.png",
    name: "Amir Kingstone",
    email: "amir@gmail.com",
    phone: "+255 675 342 345",
    address: "Tanzania, Dar es Salaam, Makumbusho",
  },
  {
    Id: "8",
    image: "/assets/mtu2.png",
    name: "Milo Jack",
    email: "hj@gmail.com",
    phone: "+255 675 342 345",
    address: "Tanzania, Dar es Salaam, Makumbusho",
  },
  {
    Id: "9",
    image: "/assets/mtu3.png",
    name: "Sam Patrick",
    email: "anna@gmail.com",
    phone: "+255 675 342 345",
    address: "Tanzania, Dar es Salaam, Makumbusho",
  },
  {
    Id: "10",
    image: "/assets/mtu7.png",
    name: "Amir Kingstone",
    email: "tina@gmail.com",
    phone: "+255 675 342 345",
    address: "Tanzania, Dar es Salaam, Makumbusho",
  },
  {
    Id: "11",
    image: "/assets/mtu5.png",
    name: "Amir Kingstone",
    email: "wewe@gmail.com",
    phone: "+255 675 342 345",
    address: "Tanzania, Dar es Salaam, Makumbusho",
  },
  {
    Id: "12",
    image: "https://docs.material-tailwind.com/img/team-3.jpg",
    name: "Jane Kitunge",
    email: "amir@gmail.com",
    phone: "+255 675 342 345",
    address: "Tanzania, Dar es Salaam, Makumbusho",
  },
];
