export const productDataList = [
  {
    Id: "1",
    image: "/assets/deki.png",
    name: "PlayStation 5 Gaming Console",
    details: "White, fairtrade certified, cotton",
    price: "TZS 2,220,000.12",
  },
  {
    Id: "2",
    image: "/assets/radioplay.png",
    name: "Mp3 Music Player",
    details: "White, fairtrade certified, cotton",
    price: "TZS 20,000.12",
  },
  {
    Id: "3",
    image: "/assets/ammitter.png",
    name: "Mini Mp3 player",
    details: "White, fairtrade certified, cotton",
    price: "TZS 15,000.12",
  },
  {
    Id: "4",
    image: "/assets/radio.png",
    name: "PlayStation 5 Gaming Console",
    details: "White, fairtrade certified, cotton",
    price: "TZS 2,220,000.12",
  },
  {
    Id: "5",
    image: "/assets/radio.png",
    name: "PlayStation 5 Gaming Console",
    details: "White, fairtrade certified, cotton",
    price: "TZS 2,220,000.12",
  },
  {
    Id: "6",
    image: "/assets/radio.png",
    name: "PlayStation 5 Gaming Console",
    details: "White, fairtrade certified, cotton",
    price: "TZS 2,220,000.12",
  },
  {
    Id: "7",
    image: "/assets/radio.png",
    name: "PlayStation 5 Gaming Console",
    details: "White, fairtrade certified, cotton",
    price: "TZS 2,220,000.12",
  },
  {
    Id: "8",
    image: "/assets/radio.png",
    name: "PlayStation 5 Gaming Console",
    details: "White, fairtrade certified, cotton",
    price: "TZS 2,220,000.12",
  },
  {
    Id: "9",
    image: "/assets/radio.png",
    name: "PlayStation 5 Gaming Console",
    details: "White, fairtrade certified, cotton",
    price: "TZS 2,220,000.12",
  },
  {
    Id: "10",
    image: "/assets/ammitter.png",
    name: "Mini Mp3 player",
    details: "White, fairtrade certified, cotton",
    price: "TZS 15,000.12",
  },
  {
    Id: "11",
    image: "/assets/radio.png",
    name: "PlayStation 5 Gaming Console",
    details: "White, fairtrade certified, cotton",
    price: "TZS 2,220,000.12",
  },
  {
    Id: "12",
    image: "/assets/radio.png",
    name: "PlayStation 5 Gaming Console",
    details: "White, fairtrade certified, cotton",
    price: "TZS 2,220,000.12",
  },
];
